### PR TITLE
Update vis_artifacts.m

### PR DESCRIPTION
**Pull request by rgougelet**
Computes scales 2x faster with 99.9% accuracy
Test code:
```
d = randn(64,500*60*60); % 64 chans, 60 mins, 500hz
tic; orig = 2*mad(d',1)'; toc;
tic; faster = 2*mad(quantile(d',1000),1)'; toc;
mean((faster-orig)./orig)
```

### CODE REVIEW

**Comment by arnodelorme** [comment]
@chkothe do you agree with the change. It looks fine to me, but I do not understand why you would have used the quantile function in the first place.

**Comment by rgougelet** [comment]
quantile downsamples while preserving scale

**Comment by arnodelorme** [comment]
So the change might work well for data that is uniform but not so much when there are outlier values?

**Comment by rgougelet** [comment]
My impression is that quantile used in this way downsamples the distribution of the data, so it will preserve the influence of outliers/the shape of the distribution. It destroys the temporal information but we're only interested in scale anyway.

**Pull request merged**
